module.exports = {
    hello: "Xin chào, mình là TMT Intelligent Chatbot. Bạn cần mình giúp gì nè (viết đầy đủ tiếng việt có dấu giúp mình)",
    err: "Có lỗi xảy ra, bạn vui lòng F5 lại trang giúp mình nhé!",
    cantfind: "Không tìm được thủ tục thỏa các yêu cầu, hãy nhập chính xác yêu cầu tên thủ tục",
    thank: "Cảm ơn bạn. Chúc bạn có một ngày vui vẻ!",
    whatyourattr: "Yêu cầu của bạn là gì?",
    showall: "Bạn có muốn xem thêm kết quả không?",
    dontunderstand: "Tôi không hiểu ý của bạn lắm. Xin hãy nhập lại.",
    reset: 'Hãy nhập thông tin bạn cần nhé',
    diadiem: ['Làm thủ tục này tại:','Bạn có thể đến'],
    nochiphi: 'Thủ tục này không cần chi phí nào',
    chiphi: ['Thủ tục này gồm các lệ phí sau: ','Bạn cần chuẩn bị lệ phí cho: '],
    thoigian: 'Thời gian làm thủ tục này là: ',
    True: 'True',
    False: 'False',
    cs: 'Câu này hỏi về màu sắc và size',
    c: "Cảm ơn quý khách đã đặt hàng tại shop",
    s: "Câu này hỏi về size",
    n: "Không hỏi về màu sắc và size",
    rep_hello: "Shop chào bạn ạ",
    rep_done: "Shop chào bạn ạ done",
    rep_inform: "Shop chào bạn ạ inform",
    rep_request: "Shop chào bạn ạ request",
    rep_feedback: "Shop chào bạn ạ feedback",
    rep_connect: "Shop chào bạn ạ connect",
    rep_order: "Bạn muốn lấy thêm sản phẩm gì không ?",
    rep_order_color: "Dạ bạn muốn lấy màu gì ạ ?",
    rep_changing: "Shop chào bạn ạ changing",
    rep_return: "Shop chào bạn ạ return"
}